name: chn-ip-task

on:
  push:
    branches: [ master ]
  workflow_dispatch:
  schedule:
    - cron: '0 */8 * * *'

jobs:
  run-get-ip-list:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Set time zone
      run: sudo timedatectl set-timezone 'Asia/Shanghai'
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Set globalization invariant mode
      run: echo "DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1" >> $GITHUB_ENV

    - name: Install dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Release --no-restore
       
    - name: Run
      run: |
        dotnet run --project china_ip_list.csproj --configuration Release
        ls -la ./bin/Release/net7.0/ || echo "Output directory not found"

    - name: Commit files
      run: |
        git config --local user.email "mayax@github.com"
        git config --local user.name "mayaxcn"
        git rm -f chn_ip.txt chnroute.txt chn_ip_v6.txt chnroute_v6.txt || true
        git commit -m "删除旧有IP文件!" || true
        cp ./bin/Release/net7.0/chn_ip.txt chn_ip.txt || echo "chn_ip.txt not found"
        cp ./bin/Release/net7.0/chnroute.txt chnroute.txt || echo "chnroute.txt not found"
        cp ./bin/Release/net7.0/chn_ip_v6.txt chn_ip_v6.txt || echo "chn_ip_v6.txt not found"
        cp ./bin/Release/net7.0/chnroute_v6.txt chnroute_v6.txt || echo "chnroute_v6.txt not found"
        git add chn_ip.txt chnroute.txt chn_ip_v6.txt chnroute_v6.txt
        git commit -m "提交新的IP文件（筛选AS4134,AS4808,AS4837,AS9808,AS4812），更新于$(date '+%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
         
    - name: Push changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: master
